#!/bin/bash

if [ -z "${1}" ]; then
  echo "Error: infra version file required"
  echo "Usage: $0 infra-versions"
  exit 1
fi

. ${1}

echo output

rm -rf output
mkdir output

wget https://releases.hashicorp.com/packer/${INFRA_PACKER_VERSION}/packer_${INFRA_PACKER_VERSION}_linux_amd64.zip
wget https://releases.hashicorp.com/terraform/${INFRA_TERRAFORM_VERSION}/terraform_${INFRA_TERRAFORM_VERSION}_linux_amd64.zip

